name: plugin_umeng_login_share
description: An umeng login plugin.
version: 0.0.3
author:
homepage:

environment:
  sdk: '>=1.23.0'
  flutter: '>=0.1.2'

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: ws.dyt.plugin.umeng.loginshare
    pluginClass: UmengLoginSharePlugin
